/**************************************************************************/
/*                                                                        */
/*                                 OCaml                                  */
/*                                                                        */
/*                      Max Slater, Jane Street                           */
/*                                                                        */
/*   Copyright 2024 Jane Street Group LLC                                 */
/*                                                                        */
/*   All rights reserved.  This file is distributed under the terms of    */
/*   the GNU Lesser General Public License version 2.1, with the          */
/*   special exception on linking described in the file LICENSE.          */
/*                                                                        */
/**************************************************************************/

#define CAML_INTERNALS

#include "caml/misc.h"
#include "caml/mlvalues.h"

#if defined __x86_64__ || defined _M_X64

// Must be kept in sync with amd64/emit.mlp

#define CAML_POPCNT      (1 << 0)
#define CAML_PREFETCHW   (1 << 1)
#define CAML_PREFETCHWT1 (1 << 2)
#define CAML_SSE3        (1 << 3)
#define CAML_SSSE3       (1 << 4)
#define CAML_SSE4_1      (1 << 5)
#define CAML_SSE4_2      (1 << 6)
#define CAML_CLMUL       (1 << 7)
#define CAML_BMI         (1 << 8)
#define CAML_BMI2        (1 << 9)

// CPUID with EAX = 1, result in ECX

#define SSE3_BIT         (1 << 0)
#define PCLMULQDQ_BIT    (1 << 1)
#define SSSE3_BIT        (1 << 9)
#define SSSE4_1_BIT      (1 << 19)
#define SSSE4_2_BIT      (1 << 20)
#define POPCNT_BIT       (1 << 23)

// CPUID with EAX = 0x80000001, result in ECX

#define ABM_BIT             (1 << 5)
#define _3DNOWPREFFETCH_BIT (1 << 8)

// CPUID with EAX = 7, ECX = 0, result in EBX

#define BMI_BIT            (1 << 3)
#define BMI2_BIT           (1 << 8)

// CPUID with EAX = 7, ECX = 0, result in ECX

#define PREFETCHWT1_BIT    (1 << 0)

// Generated by the amd64 backend, see emit.mlp.
extern uint64_t caml_required_amd64_extensions;

static void caml_cpuid(int info[4], int eax, int ecx) {
#ifdef _MSC_VER
    __cpuidex((int *)info, eax, ecx);
#else
    asm volatile (
        "cpuid"
        : "=a" (info[0]), "=b" (info[1]), "=c" (info[2]), "=d" (info[3])
        : "a" (eax), "c" (ecx)
    );
#endif
}

__attribute__((constructor))
static void caml_check_isa_extensions() {

    int info[4];
    caml_cpuid(info, 1, 0);

    if(caml_required_amd64_extensions & CAML_POPCNT) {
        if(!(info[2] & POPCNT_BIT)) {
            caml_fatal_error("Binary compiled with -fpopcnt, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_SSE3) {
        if(!(info[2] & SSE3_BIT)) {
            caml_fatal_error("Binary compiled with -msse3, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_SSSE3) {
        if(!(info[2] & SSSE3_BIT)) {
            caml_fatal_error("Binary compiled with -mssse3, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_SSE4_1) {
        if(!(info[2] & SSSE4_1_BIT)) {
            caml_fatal_error("Binary compiled with -msse41, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_SSE4_2) {
        if(!(info[2] & SSSE4_2_BIT)) {
            caml_fatal_error("Binary compiled with -msse42, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_CLMUL) {
        if(!(info[2] & PCLMULQDQ_BIT)) {
            caml_fatal_error("Binary compiled with -mpclmul, but this CPU lacks support.");
        }
    }

    caml_cpuid(info, 0x80000001, 0);

    if(caml_required_amd64_extensions & CAML_PREFETCHW) {
        if(!(info[2] & _3DNOWPREFFETCH_BIT)) {
            caml_fatal_error("Binary compiled with -mprefetchw, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_BMI) {
        // We check both the ABM and BMI bits
        if(!(info[2] & ABM_BIT)) {
            caml_fatal_error("Binary compiled with -mbmi, but this CPU lacks support.");
        }
    }

    caml_cpuid(info, 7, 0);

    if(caml_required_amd64_extensions & CAML_BMI) {
        if(!(info[1] & BMI_BIT)) {
            caml_fatal_error("Binary compiled with -mbmi, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_BMI2) {
        if(!(info[1] & BMI2_BIT)) {
            caml_fatal_error("Binary compiled with -mbmi2, but this CPU lacks support.");
        }
    }
    if(caml_required_amd64_extensions & CAML_PREFETCHWT1) {
        if(!(info[2] & PREFETCHWT1_BIT)) {
            caml_fatal_error("Binary compiled with -mprefetchwt1, but this CPU lacks support.");
        }
    }
}

#endif /* No aarch64 extensions are currently available. */
